// Add languages here: { code, name (button label), tts (SpeechSynthesis lang) }
export const languages = [
  { code: 'en', name: 'EN', tts: 'en-US' },
  { code: 'zh', name: '中文', tts: 'zh-CN' },
  { code: 'es', name: 'ES', tts: 'es-ES' },
]

// Add sets here: { id, name (per language), cards }
// card.word = word per language
// card.art = a named motif with a matching asset file src/assets/<name>.svg,
//         or { n: 1..20 } for numbers, or { c: 'red'|'blue'|'yellow'|'green'|'purple' } for colors
export const sets = [
  {
    id: 'numbers',
    name: { en: 'Numbers', zh: '数字', es: 'Números' },
    cards: [
      { word: { en: 'one', zh: '一', es: 'uno' }, art: { n: 1 } },
      { word: { en: 'two', zh: '二', es: 'dos' }, art: { n: 2 } },
      { word: { en: 'three', zh: '三', es: 'tres' }, art: { n: 3 } },
      { word: { en: 'four', zh: '四', es: 'cuatro' }, art: { n: 4 } },
      { word: { en: 'five', zh: '五', es: 'cinco' }, art: { n: 5 } },
      { word: { en: 'six', zh: '六', es: 'seis' }, art: { n: 6 } },
      { word: { en: 'seven', zh: '七', es: 'siete' }, art: { n: 7 } },
      { word: { en: 'eight', zh: '八', es: 'ocho' }, art: { n: 8 } },
      { word: { en: 'nine', zh: '九', es: 'nueve' }, art: { n: 9 } },
      { word: { en: 'ten', zh: '十', es: 'diez' }, art: { n: 10 } },
    ],
  },
  {
    id: 'fruits',
    name: { en: 'Fruits', zh: '水果', es: 'Frutas' },
    cards: [
      { word: { en: 'apple', zh: '苹果', es: 'manzana' }, art: 'apple' },
      { word: { en: 'banana', zh: '香蕉', es: 'plátano' }, art: 'banana' },
      { word: { en: 'orange', zh: '橙子', es: 'naranja' }, art: 'orange' },
      { word: { en: 'strawberry', zh: '草莓', es: 'fresa' }, art: 'strawberry' },
      { word: { en: 'grape', zh: '葡萄', es: 'uva' }, art: 'grape' },
      { word: { en: 'pear', zh: '梨', es: 'pera' }, art: 'pear' },
      { word: { en: 'watermelon', zh: '西瓜', es: 'sandía' }, art: 'watermelon' },
      { word: { en: 'peach', zh: '桃子', es: 'melocotón' }, art: 'peach' },
      { word: { en: 'lemon', zh: '柠檬', es: 'limón' }, art: 'lemon' },
      { word: { en: 'mango', zh: '芒果', es: 'mango' }, art: 'mango' },
      { word: { en: 'cherry', zh: '樱桃', es: 'cereza' }, art: 'cherry' },
      { word: { en: 'pineapple', zh: '菠萝', es: 'piña' }, art: 'pineapple' },
      { word: { en: 'kiwi', zh: '猕猴桃', es: 'kiwi' }, art: 'kiwi' },
      { word: { en: 'coconut', zh: '椰子', es: 'coco' }, art: 'coconut' },
      { word: { en: 'plum', zh: '李子', es: 'ciruela' }, art: 'plum' },
    ],
  },
  {
    id: 'animals',
    name: { en: 'Animals', zh: '动物', es: 'Animales' },
    cards: [
      { word: { en: 'cat', zh: '猫', es: 'gato' }, art: 'cat' },
      { word: { en: 'dog', zh: '狗', es: 'perro' }, art: 'dog' },
      { word: { en: 'bunny', zh: '兔子', es: 'conejo' }, art: 'bunny' },
      { word: { en: 'bird', zh: '鸟', es: 'pájaro' }, art: 'bird' },
      { word: { en: 'fish', zh: '鱼', es: 'pez' }, art: 'fish' },
      { word: { en: 'elephant', zh: '大象', es: 'elefante' }, art: 'elephant' },
      { word: { en: 'turtle', zh: '乌龟', es: 'tortuga' }, art: 'turtle' },
      { word: { en: 'penguin', zh: '企鹅', es: 'pingüino' }, art: 'penguin' },
      { word: { en: 'bear', zh: '熊', es: 'oso' }, art: 'bear' },
      { word: { en: 'fox', zh: '狐狸', es: 'zorro' }, art: 'fox' },
      { word: { en: 'frog', zh: '青蛙', es: 'rana' }, art: 'frog' },
      { word: { en: 'owl', zh: '猫头鹰', es: 'búho' }, art: 'owl' },
      { word: { en: 'parrot', zh: '鹦鹉', es: 'loro' }, art: 'parrot' },
      { word: { en: 'squirrel', zh: '松鼠', es: 'ardilla' }, art: 'squirrel' },
      { word: { en: 'hedgehog', zh: '刺猬', es: 'erizo' }, art: 'hedgehog' },
      { word: { en: 'deer', zh: '鹿', es: 'ciervo' }, art: 'deer' },
    ],
  },
  {
    id: 'colors',
    name: { en: 'Colors', zh: '颜色', es: 'Colores' },
    cards: [
      { word: { en: 'red', zh: '红色', es: 'rojo' }, art: { c: 'red' } },
      { word: { en: 'blue', zh: '蓝色', es: 'azul' }, art: { c: 'blue' } },
      { word: { en: 'yellow', zh: '黄色', es: 'amarillo' }, art: { c: 'yellow' } },
      { word: { en: 'green', zh: '绿色', es: 'verde' }, art: { c: 'green' } },
      { word: { en: 'purple', zh: '紫色', es: 'morado' }, art: { c: 'purple' } },
    ],
  },
  {
    id: 'food',
    name: { en: 'Food', zh: '食物', es: 'Comida' },
    cards: [
      { word: { en: 'bread', zh: '面包', es: 'pan' }, art: 'bread' },
      { word: { en: 'egg', zh: '鸡蛋', es: 'huevo' }, art: 'egg' },
      { word: { en: 'milk', zh: '牛奶', es: 'leche' }, art: 'milk' },
      { word: { en: 'cheese', zh: '奶酪', es: 'queso' }, art: 'cheese' },
      { word: { en: 'pizza', zh: '披萨', es: 'pizza' }, art: 'pizza' },
      { word: { en: 'burger', zh: '汉堡', es: 'hamburguesa' }, art: 'burger' },
      { word: { en: 'donut', zh: '甜甜圈', es: 'dona' }, art: 'donut' },
      { word: { en: 'ice cream', zh: '冰淇淋', es: 'helado' }, art: 'icecream' },
      { word: { en: 'cookie', zh: '饼干', es: 'galleta' }, art: 'cookie' },
      { word: { en: 'noodles', zh: '面条', es: 'fideos' }, art: 'noodles' },
      { word: { en: 'soup', zh: '汤', es: 'sopa' }, art: 'soup' },
      { word: { en: 'sandwich', zh: '三明治', es: 'sándwich' }, art: 'sandwich' },
    ],
  },
  {
    id: 'vehicles',
    name: { en: 'Vehicles', zh: '交通工具', es: 'Vehículos' },
    cards: [
      { word: { en: 'car', zh: '汽车', es: 'coche' }, art: 'car' },
      { word: { en: 'bus', zh: '公共汽车', es: 'autobús' }, art: 'bus' },
      { word: { en: 'train', zh: '火车', es: 'tren' }, art: 'train' },
      { word: { en: 'bicycle', zh: '自行车', es: 'bicicleta' }, art: 'bicycle' },
      { word: { en: 'plane', zh: '飞机', es: 'avión' }, art: 'plane' },
      { word: { en: 'boat', zh: '船', es: 'barco' }, art: 'boat' },
      { word: { en: 'rocket', zh: '火箭', es: 'cohete' }, art: 'rocket' },
      { word: { en: 'helicopter', zh: '直升机', es: 'helicóptero' }, art: 'helicopter' },
      { word: { en: 'tractor', zh: '拖拉机', es: 'tractor' }, art: 'tractor' },
      { word: { en: 'truck', zh: '卡车', es: 'camión' }, art: 'truck' },
    ],
  },
  {
    id: 'nature',
    name: { en: 'Nature', zh: '自然', es: 'Naturaleza' },
    cards: [
      { word: { en: 'tree', zh: '树', es: 'árbol' }, art: 'tree' },
      { word: { en: 'flower', zh: '花', es: 'flor' }, art: 'flower' },
      { word: { en: 'sun', zh: '太阳', es: 'sol' }, art: 'sun' },
      { word: { en: 'moon', zh: '月亮', es: 'luna' }, art: 'moon' },
      { word: { en: 'cloud', zh: '云朵', es: 'nube' }, art: 'cloud' },
      { word: { en: 'rain', zh: '雨', es: 'lluvia' }, art: 'rain' },
      { word: { en: 'snowflake', zh: '雪花', es: 'copo de nieve' }, art: 'snowflake' },
      { word: { en: 'rainbow', zh: '彩虹', es: 'arcoíris' }, art: 'rainbow' },
      { word: { en: 'wind', zh: '风', es: 'viento' }, art: 'wind' },
      { word: { en: 'lightning', zh: '闪电', es: 'rayo' }, art: 'lightning' },
      { word: { en: 'leaf', zh: '树叶', es: 'hoja' }, art: 'leaf' },
    ],
  },
  {
    id: 'shapes',
    name: { en: 'Shapes', zh: '形状', es: 'Formas' },
    cards: [
      { word: { en: 'circle', zh: '圆形', es: 'círculo' }, art: 'circle' },
      { word: { en: 'square', zh: '正方形', es: 'cuadrado' }, art: 'square' },
      { word: { en: 'triangle', zh: '三角形', es: 'triángulo' }, art: 'triangle' },
      { word: { en: 'star', zh: '星星', es: 'estrella' }, art: 'star' },
      { word: { en: 'heart', zh: '心', es: 'corazón' }, art: 'heart' },
      { word: { en: 'diamond', zh: '菱形', es: 'rombo' }, art: 'diamond' },
      { word: { en: 'oval', zh: '椭圆形', es: 'óvalo' }, art: 'oval' },
      { word: { en: 'rectangle', zh: '长方形', es: 'rectángulo' }, art: 'rectangle' },
      { word: { en: 'crescent', zh: '月牙', es: 'medialuna' }, art: 'crescent' },
      { word: { en: 'arrow', zh: '箭头', es: 'flecha' }, art: 'arrow' },
    ],
  },
  {
    id: 'vegetables',
    name: { en: 'Vegetables', zh: '蔬菜', es: 'Verduras' },
    cards: [
      { word: { en: 'carrot', zh: '胡萝卜', es: 'zanahoria' }, art: 'carrot' },
      { word: { en: 'tomato', zh: '番茄', es: 'tomate' }, art: 'tomato' },
      { word: { en: 'broccoli', zh: '西兰花', es: 'brócoli' }, art: 'broccoli' },
      { word: { en: 'corn', zh: '玉米', es: 'maíz' }, art: 'corn' },
      { word: { en: 'pumpkin', zh: '南瓜', es: 'calabaza' }, art: 'pumpkin' },
      { word: { en: 'cucumber', zh: '黄瓜', es: 'pepino' }, art: 'cucumber' },
      { word: { en: 'mushroom', zh: '蘑菇', es: 'champiñón' }, art: 'mushroom' },
      { word: { en: 'eggplant', zh: '茄子', es: 'berenjena' }, art: 'eggplant' },
      { word: { en: 'pepper', zh: '辣椒', es: 'pimiento' }, art: 'pepper' },
      { word: { en: 'potato', zh: '土豆', es: 'patata' }, art: 'potato' },
      { word: { en: 'onion', zh: '洋葱', es: 'cebolla' }, art: 'onion' },
      { word: { en: 'garlic', zh: '大蒜', es: 'ajo' }, art: 'garlic' },
    ],
  },
  {
    id: 'drinks',
    name: { en: 'Drinks', zh: '饮料', es: 'Bebidas' },
    cards: [
      { word: { en: 'juice', zh: '果汁', es: 'zumo' }, art: 'juice' },
      { word: { en: 'water', zh: '水', es: 'agua' }, art: 'water' },
      { word: { en: 'tea', zh: '茶', es: 'té' }, art: 'tea' },
      { word: { en: 'lemonade', zh: '柠檬水', es: 'limonada' }, art: 'lemonade' },
      { word: { en: 'coffee', zh: '咖啡', es: 'café' }, art: 'coffee' },
    ],
  },
  {
    id: 'farm',
    name: { en: 'Farm', zh: '农场', es: 'Granja' },
    cards: [
      { word: { en: 'pig', zh: '猪', es: 'cerdo' }, art: 'pig' },
      { word: { en: 'cow', zh: '牛', es: 'vaca' }, art: 'cow' },
      { word: { en: 'hen', zh: '母鸡', es: 'gallina' }, art: 'hen' },
      { word: { en: 'sheep', zh: '绵羊', es: 'oveja' }, art: 'sheep' },
      { word: { en: 'horse', zh: '马', es: 'caballo' }, art: 'horse' },
      { word: { en: 'duck', zh: '鸭子', es: 'pato' }, art: 'duck' },
      { word: { en: 'rooster', zh: '公鸡', es: 'gallo' }, art: 'rooster' },
      { word: { en: 'goat', zh: '山羊', es: 'cabra' }, art: 'goat' },
    ],
  },
  {
    id: 'wild',
    name: { en: 'Wild Animals', zh: '野生动物', es: 'Animales salvajes' },
    cards: [
      { word: { en: 'monkey', zh: '猴子', es: 'mono' }, art: 'monkey' },
      { word: { en: 'panda', zh: '熊猫', es: 'panda' }, art: 'panda' },
      { word: { en: 'lion', zh: '狮子', es: 'león' }, art: 'lion' },
      { word: { en: 'giraffe', zh: '长颈鹿', es: 'jirafa' }, art: 'giraffe' },
      { word: { en: 'zebra', zh: '斑马', es: 'cebra' }, art: 'zebra' },
      { word: { en: 'snake', zh: '蛇', es: 'serpiente' }, art: 'snake' },
      { word: { en: 'hippo', zh: '河马', es: 'hipopótamo' }, art: 'hippo' },
      { word: { en: 'tiger', zh: '老虎', es: 'tigre' }, art: 'tiger' },
      { word: { en: 'koala', zh: '考拉', es: 'koala' }, art: 'koala' },
      { word: { en: 'camel', zh: '骆驼', es: 'camello' }, art: 'camel' },
    ],
  },
  {
    id: 'sea',
    name: { en: 'Sea', zh: '海洋', es: 'Mar' },
    cards: [
      { word: { en: 'whale', zh: '鲸鱼', es: 'ballena' }, art: 'whale' },
      { word: { en: 'dolphin', zh: '海豚', es: 'delfín' }, art: 'dolphin' },
      { word: { en: 'octopus', zh: '章鱼', es: 'pulpo' }, art: 'octopus' },
      { word: { en: 'crab', zh: '螃蟹', es: 'cangrejo' }, art: 'crab' },
      { word: { en: 'starfish', zh: '海星', es: 'estrella de mar' }, art: 'starfish' },
      { word: { en: 'shark', zh: '鲨鱼', es: 'tiburón' }, art: 'shark' },
      { word: { en: 'jellyfish', zh: '水母', es: 'medusa' }, art: 'jellyfish' },
      { word: { en: 'shell', zh: '贝壳', es: 'concha' }, art: 'shell' },
    ],
  },
  {
    id: 'bugs',
    name: { en: 'Bugs', zh: '虫子', es: 'Bichos' },
    cards: [
      { word: { en: 'butterfly', zh: '蝴蝶', es: 'mariposa' }, art: 'butterfly' },
      { word: { en: 'ladybug', zh: '瓢虫', es: 'mariquita' }, art: 'ladybug' },
      { word: { en: 'bee', zh: '蜜蜂', es: 'abeja' }, art: 'bee' },
      { word: { en: 'snail', zh: '蜗牛', es: 'caracol' }, art: 'snail' },
      { word: { en: 'caterpillar', zh: '毛毛虫', es: 'oruga' }, art: 'caterpillar' },
      { word: { en: 'dragonfly', zh: '蜻蜓', es: 'libélula' }, art: 'dragonfly' },
      { word: { en: 'ant', zh: '蚂蚁', es: 'hormiga' }, art: 'ant' },
      { word: { en: 'worm', zh: '蚯蚓', es: 'gusano' }, art: 'worm' },
    ],
  },
  {
    id: 'clothes',
    name: { en: 'Clothes', zh: '衣服', es: 'Ropa' },
    cards: [
      { word: { en: 'shirt', zh: '衬衫', es: 'camisa' }, art: 'shirt' },
      { word: { en: 'pants', zh: '裤子', es: 'pantalones' }, art: 'pants' },
      { word: { en: 'dress', zh: '连衣裙', es: 'vestido' }, art: 'dress' },
      { word: { en: 'hat', zh: '帽子', es: 'sombrero' }, art: 'hat' },
      { word: { en: 'socks', zh: '袜子', es: 'calcetines' }, art: 'socks' },
      { word: { en: 'shoes', zh: '鞋子', es: 'zapatos' }, art: 'shoes' },
      { word: { en: 'scarf', zh: '围巾', es: 'bufanda' }, art: 'scarf' },
      { word: { en: 'glove', zh: '手套', es: 'guante' }, art: 'glove' },
      { word: { en: 'sweater', zh: '毛衣', es: 'suéter' }, art: 'sweater' },
      { word: { en: 'boots', zh: '靴子', es: 'botas' }, art: 'boots' },
    ],
  },
  {
    id: 'body',
    name: { en: 'My Body', zh: '身体', es: 'Mi cuerpo' },
    cards: [
      { word: { en: 'eye', zh: '眼睛', es: 'ojo' }, art: 'eye' },
      { word: { en: 'ear', zh: '耳朵', es: 'oreja' }, art: 'ear' },
      { word: { en: 'nose', zh: '鼻子', es: 'nariz' }, art: 'nose' },
      { word: { en: 'mouth', zh: '嘴巴', es: 'boca' }, art: 'mouth' },
      { word: { en: 'tooth', zh: '牙齿', es: 'diente' }, art: 'tooth' },
      { word: { en: 'hand', zh: '手', es: 'mano' }, art: 'hand' },
      { word: { en: 'foot', zh: '脚', es: 'pie' }, art: 'foot' },
      { word: { en: 'tongue', zh: '舌头', es: 'lengua' }, art: 'tongue' },
      { word: { en: 'arm', zh: '手臂', es: 'brazo' }, art: 'arm' },
      { word: { en: 'leg', zh: '腿', es: 'pierna' }, art: 'leg' },
    ],
  },
  {
    id: 'toys',
    name: { en: 'Toys', zh: '玩具', es: 'Juguetes' },
    cards: [
      { word: { en: 'ball', zh: '球', es: 'pelota' }, art: 'ball' },
      { word: { en: 'teddy bear', zh: '泰迪熊', es: 'oso de peluche' }, art: 'teddy' },
      { word: { en: 'kite', zh: '风筝', es: 'cometa' }, art: 'kite' },
      { word: { en: 'balloon', zh: '气球', es: 'globo' }, art: 'balloon' },
      { word: { en: 'doll', zh: '娃娃', es: 'muñeca' }, art: 'doll' },
      { word: { en: 'blocks', zh: '积木', es: 'bloques' }, art: 'blocks' },
      { word: { en: 'slide', zh: '滑梯', es: 'tobogán' }, art: 'slide' },
      { word: { en: 'swing', zh: '秋千', es: 'columpio' }, art: 'swing' },
      { word: { en: 'puppet', zh: '手偶', es: 'marioneta' }, art: 'puppet' },
      { word: { en: 'robot', zh: '机器人', es: 'robot' }, art: 'robot' },
      { word: { en: 'puzzle', zh: '拼图', es: 'rompecabezas' }, art: 'puzzle' },
    ],
  },
  {
    id: 'home',
    name: { en: 'Home', zh: '家', es: 'Hogar' },
    cards: [
      { word: { en: 'house', zh: '房子', es: 'casa' }, art: 'house' },
      { word: { en: 'bed', zh: '床', es: 'cama' }, art: 'bed' },
      { word: { en: 'chair', zh: '椅子', es: 'silla' }, art: 'chair' },
      { word: { en: 'table', zh: '桌子', es: 'mesa' }, art: 'table' },
      { word: { en: 'lamp', zh: '台灯', es: 'lámpara' }, art: 'lamp' },
      { word: { en: 'book', zh: '书', es: 'libro' }, art: 'book' },
      { word: { en: 'cup', zh: '杯子', es: 'taza' }, art: 'cup' },
      { word: { en: 'plate', zh: '盘子', es: 'plato' }, art: 'plate' },
      { word: { en: 'spoon', zh: '勺子', es: 'cuchara' }, art: 'spoon' },
      { word: { en: 'sofa', zh: '沙发', es: 'sofá' }, art: 'sofa' },
      { word: { en: 'mirror', zh: '镜子', es: 'espejo' }, art: 'mirror' },
    ],
  },
  {
    id: 'music',
    name: { en: 'Music', zh: '音乐', es: 'Música' },
    cards: [
      { word: { en: 'piano', zh: '钢琴', es: 'piano' }, art: 'piano' },
      { word: { en: 'guitar', zh: '吉他', es: 'guitarra' }, art: 'guitar' },
      { word: { en: 'drum', zh: '鼓', es: 'tambor' }, art: 'drum' },
      { word: { en: 'trumpet', zh: '小号', es: 'trompeta' }, art: 'trumpet' },
      { word: { en: 'violin', zh: '小提琴', es: 'violín' }, art: 'violin' },
      { word: { en: 'tambourine', zh: '铃鼓', es: 'pandereta' }, art: 'tambourine' },
      { word: { en: 'flute', zh: '长笛', es: 'flauta' }, art: 'flute' },
      { word: { en: 'maracas', zh: '沙锤', es: 'maracas' }, art: 'maracas' },
      { word: { en: 'xylophone', zh: '木琴', es: 'xilófono' }, art: 'xylophone' },
      { word: { en: 'microphone', zh: '麦克风', es: 'micrófono' }, art: 'microphone' },
    ],
  },
  {
    id: 'helpers',
    name: { en: 'Helpers', zh: '职业', es: 'Ayudantes' },
    cards: [
      { word: { en: 'doctor', zh: '医生', es: 'médico' }, art: 'doctor' },
      { word: { en: 'nurse', zh: '护士', es: 'enfermera' }, art: 'nurse' },
      { word: { en: 'police', zh: '警察', es: 'policía' }, art: 'police' },
      { word: { en: 'firefighter', zh: '消防员', es: 'bombero' }, art: 'firefighter' },
      { word: { en: 'teacher', zh: '老师', es: 'maestro' }, art: 'teacher' },
      { word: { en: 'chef', zh: '厨师', es: 'cocinero' }, art: 'chef' },
      { word: { en: 'farmer', zh: '农民', es: 'granjero' }, art: 'farmer' },
      { word: { en: 'pilot', zh: '飞行员', es: 'piloto' }, art: 'pilot' },
      { word: { en: 'builder', zh: '建筑工人', es: 'albañil' }, art: 'builder' },
      { word: { en: 'vet', zh: '兽医', es: 'veterinario' }, art: 'vet' },
    ],
  },
  {
    id: 'places',
    name: { en: 'Places', zh: '地点', es: 'Lugares' },
    cards: [
      { word: { en: 'park', zh: '公园', es: 'parque' }, art: 'park' },
      { word: { en: 'zoo', zh: '动物园', es: 'zoológico' }, art: 'zoo' },
      { word: { en: 'beach', zh: '海滩', es: 'playa' }, art: 'beach' },
      { word: { en: 'school', zh: '学校', es: 'escuela' }, art: 'school' },
      { word: { en: 'hospital', zh: '医院', es: 'hospital' }, art: 'hospital' },
      { word: { en: 'store', zh: '商店', es: 'tienda' }, art: 'store' },
      { word: { en: 'market', zh: '市场', es: 'mercado' }, art: 'market' },
      { word: { en: 'playground', zh: '游乐场', es: 'parque infantil' }, art: 'playground' },
      { word: { en: 'cinema', zh: '电影院', es: 'cine' }, art: 'cinema' },
      { word: { en: 'library', zh: '图书馆', es: 'biblioteca' }, art: 'library' },
    ],
  },
  {
    id: 'seasons',
    name: { en: 'Seasons', zh: '季节', es: 'Estaciones' },
    cards: [
      { word: { en: 'spring', zh: '春天', es: 'primavera' }, art: 'spring' },
      { word: { en: 'summer', zh: '夏天', es: 'verano' }, art: 'summer' },
      { word: { en: 'autumn', zh: '秋天', es: 'otoño' }, art: 'autumn' },
      { word: { en: 'winter', zh: '冬天', es: 'invierno' }, art: 'winter' },
    ],
  },
  {
    id: 'days',
    name: { en: 'Days', zh: '星期', es: 'Días' },
    cards: [
      { word: { en: 'Monday', zh: '星期一', es: 'lunes' }, art: 'monday' },
      { word: { en: 'Tuesday', zh: '星期二', es: 'martes' }, art: 'tuesday' },
      { word: { en: 'Wednesday', zh: '星期三', es: 'miércoles' }, art: 'wednesday' },
      { word: { en: 'Thursday', zh: '星期四', es: 'jueves' }, art: 'thursday' },
      { word: { en: 'Friday', zh: '星期五', es: 'viernes' }, art: 'friday' },
      { word: { en: 'Saturday', zh: '星期六', es: 'sábado' }, art: 'saturday' },
      { word: { en: 'Sunday', zh: '星期日', es: 'domingo' }, art: 'sunday' },
    ],
  },
  {
    id: 'emotions',
    name: { en: 'Feelings', zh: '情绪', es: 'Emociones' },
    cards: [
      { word: { en: 'happy', zh: '开心', es: 'feliz' }, art: 'happy' },
      { word: { en: 'sad', zh: '难过', es: 'triste' }, art: 'sad' },
      { word: { en: 'angry', zh: '生气', es: 'enojado' }, art: 'angry' },
      { word: { en: 'sleepy', zh: '困了', es: 'con sueño' }, art: 'sleepy' },
    ],
  },
  {
    id: 'breakfast',
    name: { en: 'Breakfast', zh: '早餐', es: 'Desayuno' },
    cards: [
      { word: { en: 'pancake', zh: '煎饼', es: 'panqueque' }, art: 'pancake' },
      { word: { en: 'toast', zh: '吐司', es: 'tostada' }, art: 'toast' },
      { word: { en: 'jam', zh: '果酱', es: 'mermelada' }, art: 'jam' },
    ],
  },
  {
    id: 'nature2',
    name: { en: 'More Nature', zh: '更多自然', es: 'Más naturaleza' },
    cards: [
      { word: { en: 'mountain', zh: '山', es: 'montaña' }, art: 'mountain' },
      { word: { en: 'river', zh: '河', es: 'río' }, art: 'river' },
      { word: { en: 'grass', zh: '草', es: 'hierba' }, art: 'grass' },
      { word: { en: 'cactus', zh: '仙人掌', es: 'cactus' }, art: 'cactus' },
      { word: { en: 'bamboo', zh: '竹子', es: 'bambú' }, art: 'bamboo' },
      { word: { en: 'puddle', zh: '水洼', es: 'charco' }, art: 'puddle' },
    ],
  },
  {
    id: 'sweets',
    name: { en: 'Sweets', zh: '甜食', es: 'Dulces' },
    cards: [
      { word: { en: 'candy', zh: '糖果', es: 'caramelo' }, art: 'candy' },
      { word: { en: 'lollipop', zh: '棒棒糖', es: 'piruleta' }, art: 'lollipop' },
      { word: { en: 'chocolate', zh: '巧克力', es: 'chocolate' }, art: 'chocolate' },
      { word: { en: 'cupcake', zh: '纸杯蛋糕', es: 'pastelito' }, art: 'cupcake' },
      { word: { en: 'honey', zh: '蜂蜜', es: 'miel' }, art: 'honey' },
      { word: { en: 'popcorn', zh: '爆米花', es: 'palomitas' }, art: 'popcorn' },
    ],
  },
]
